[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
figlet-rs = "0.1.5"
rand = "0.9.0"
reedline = "0.39.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
